import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from fpdf import FPDF
from datetime import datetime
import pandas as pd
import plotly.express as px
import plotly.io as pio


class BusinessReport(FPDF):
    def header(self):
        self.set_fill_color(15, 17, 23)
        self.rect(0, 0, 210, 25, 'F')
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(108, 99, 255)
        self.cell(0, 15, "QueryMind", ln=False, align="L")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(139, 143, 168)
        self.cell(0, 15, f"Business Intelligence Report  |  {datetime.now().strftime('%B %d, %Y')}", ln=True, align="R")
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(139, 143, 168)
        self.cell(0, 10, f"Generated by QueryMind AI  |  Page {self.page_no()}", align="C")

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(108, 99, 255)
        self.set_fill_color(30, 33, 48)
        self.cell(0, 10, title, ln=True, fill=True)
        self.ln(2)

    def question_block(self, question: str):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(72, 202, 228)
        clean = question.encode("latin-1", "ignore").decode("latin-1")
        self.cell(0, 8, f"Q: {clean}", ln=True)

    def sql_block(self, sql: str):
        self.set_font("Courier", "", 8)
        self.set_text_color(180, 180, 180)
        self.set_fill_color(20, 22, 35)
        clean = sql.encode("latin-1", "ignore").decode("latin-1")
        self.multi_cell(0, 5, clean, fill=True)
        self.ln(2)

    def insight_block(self, text: str):
        self.set_font("Helvetica", "", 9)
        self.set_text_color(200, 200, 200)
        clean = text.encode("latin-1", "ignore").decode("latin-1")
        self.multi_cell(0, 5, clean)
        self.ln(3)

    def add_table(self, df: pd.DataFrame):
        if df.empty:
            return

        df_display = df.head(10)
        col_width = 190 / len(df_display.columns)

        # Header row
        self.set_font("Helvetica", "B", 8)
        self.set_fill_color(108, 99, 255)
        self.set_text_color(255, 255, 255)
        for col in df_display.columns:
            clean_col = str(col).encode("latin-1", "ignore").decode("latin-1")
            self.cell(col_width, 7, clean_col[:15], border=0, fill=True, align="C")
        self.ln()

        # Data rows
        self.set_font("Helvetica", "", 8)
        for i, row in df_display.iterrows():
            if i % 2 == 0:
                self.set_fill_color(30, 33, 48)
            else:
                self.set_fill_color(20, 22, 35)
            self.set_text_color(200, 200, 200)
            for val in row:
                clean_val = str(val).encode("latin-1", "ignore").decode("latin-1")
                self.cell(col_width, 6, clean_val[:15], border=0, fill=True, align="C")
            self.ln()
        self.ln(4)


def generate_chart_image(df: pd.DataFrame, question: str, index: int) -> str:
    numeric_cols = df.select_dtypes(include="number").columns.tolist()
    text_cols = df.select_dtypes(exclude="number").columns.tolist()

    if not numeric_cols or not text_cols:
        return None

    try:
        clean_title = question.encode("latin-1", "ignore").decode("latin-1")
        fig = px.bar(
            df.head(10),
            x=text_cols[0],
            y=numeric_cols[0],
            title=clean_title,
            template="plotly_dark",
            color=text_cols[0],
            color_discrete_sequence=px.colors.sequential.Purples_r
        )
        fig.update_layout(
            width=700, height=350,
            plot_bgcolor="rgba(20,22,35,1)",
            paper_bgcolor="rgba(20,22,35,1)",
            showlegend=False
        )

        path = f"/tmp/chart_{index}.png"
        pio.write_image(fig, path, format="png")
        return path
    except:
        return None


def create_report(report_data: list) -> bytes:
    pdf = BusinessReport()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Cover
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(255, 255, 255)
    pdf.ln(5)
    pdf.cell(0, 15, "Business Intelligence Report", ln=True, align="C")
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(139, 143, 168)
    pdf.cell(0, 8, f"Generated on {datetime.now().strftime('%B %d, %Y at %H:%M')}", ln=True, align="C")
    pdf.cell(0, 8, f"Total Queries Analyzed: {len(report_data)}", ln=True, align="C")
    pdf.ln(10)

    # Summary bar
    pdf.set_fill_color(30, 33, 48)
    pdf.rect(10, pdf.get_y(), 190, 15, 'F')
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(108, 99, 255)
    pdf.cell(0, 15, f"  QueryMind AI  |  Powered by Groq Llama 3  |  {len(report_data)} insights generated", ln=True)
    pdf.ln(8)

    # Each query
    for i, item in enumerate(report_data):
        pdf.section_title(f"Query {i + 1}")
        pdf.question_block(item["question"])
        pdf.ln(2)

        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(139, 143, 168)
        pdf.cell(0, 6, "Generated SQL:", ln=True)
        pdf.sql_block(item["sql"])

        if item["df"] is not None and not item["df"].empty:
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(139, 143, 168)
            pdf.cell(0, 6, f"Results ({min(10, len(item['df']))} of {len(item['df'])} rows):", ln=True)
            pdf.add_table(item["df"])

            chart_path = generate_chart_image(item["df"], item["question"], i)
            if chart_path and os.path.exists(chart_path):
                try:
                    pdf.image(chart_path, x=10, w=190)
                    pdf.ln(4)
                except:
                    pass

        if item.get("insight"):
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(72, 202, 228)
            pdf.cell(0, 6, "AI Insight:", ln=True)
            pdf.insight_block(item["insight"])

        if item.get("anomaly"):
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(255, 165, 0)
            pdf.cell(0, 6, "Anomaly Check:", ln=True)
            pdf.insight_block(item["anomaly"])

        pdf.ln(5)

        if i < len(report_data) - 1:
            pdf.add_page()

    return bytes(pdf.output())